spring.application.name=NetworkInventoryTask

spring.jpa.hibernate.ddl-auto=none

spring.datasource.username=sa
spring.datasource.password=<YourStrong@Passw0rd>
spring.datasource.url=jdbc:sqlserver://10.250.235.10:1433;databaseName=nis_nikolay;encrypt=true;trustServerCertificate=true
